DROP TABLE IF EXISTS band;

CREATE TABLE band (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    band_name TEXT NOT NULL
);

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL
);